<a href="https://colab.research.google.com/github/ashishb321/DATA-VIZ/blob/main/NUMPY_CRASH_COURSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
!pip install numpy

In [74]:
import numpy as np

CREATION OF ARRAYS

In [75]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2),7)#similar to zeros and ones implementation minor change is that 7 replaces all the zeros
ones = np.ones((2,2,2))


In [76]:
data

array([[[0.74787687, 0.23371111, 0.68597185, 0.9144645 ],
        [0.88541515, 0.72853479, 0.28201572, 0.45144807],
        [0.11069352, 0.67192323, 0.86386788, 0.44515546]],

       [[0.18598314, 0.93517955, 0.38444154, 0.03532012],
        [0.62706473, 0.49197108, 0.59434518, 0.67246978],
        [0.96372605, 0.40979046, 0.79372034, 0.73144647]]])

In [77]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [78]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [79]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [80]:
arr = np.array([[1,2,3,4],[1,2,3,4]])


In [81]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [82]:
type(arr)

numpy.ndarray

READING OF ARRAYS 

In [83]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype



In [84]:
types 

dtype('float64')

In [85]:
#slicing 
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]


In [86]:
arr 

array([[0.74787687, 0.23371111, 0.68597185, 0.9144645 ],
       [0.88541515, 0.72853479, 0.28201572, 0.45144807],
       [0.11069352, 0.67192323, 0.86386788, 0.44515546]])

In [87]:
slicer

array([[0.74787687, 0.23371111, 0.68597185, 0.9144645 ],
       [0.88541515, 0.72853479, 0.28201572, 0.45144807]])

In [88]:
reverse

array([[0.18598314, 0.93517955, 0.38444154, 0.03532012],
       [0.62706473, 0.49197108, 0.59434518, 0.67246978],
       [0.96372605, 0.40979046, 0.79372034, 0.73144647]])

UPDATING THE VALUES 

In [89]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [90]:
list1

array([0.76002008, 0.56181715, 0.6411166 , 0.87622022, 0.26049193,
       0.65993068, 0.36950358, 0.68366009, 0.84633077, 0.34017401])

In [91]:
list2

array([0.67073571, 0.86746161, 0.41627093, 0.2319951 , 0.20151958,
       0.57525984, 0.09414071, 0.71066036, 0.91984105, 0.62478035])

In [92]:
#Basic Math functions 
add = np.add(list1,list2)
subtract = np.subtract(list1,list2)
multiply = np.multiply(list1,list2)
divide = np.divide(list1,list2)
dot = np.dot(list1,list2)

In [93]:
add

array([1.43075579, 1.42927875, 1.05738753, 1.10821533, 0.4620115 ,
       1.23519052, 0.46364429, 1.39432046, 1.76617182, 0.96495437])

In [94]:
subtract

array([ 0.08928436, -0.30564446,  0.22484567,  0.64422512,  0.05897235,
        0.08467083,  0.27536287, -0.02700027, -0.07351029, -0.28460634])

In [95]:
multiply

array([0.50977261, 0.4873548 , 0.2668782 , 0.2032788 , 0.05249422,
       0.37963162, 0.03478533, 0.48585013, 0.77848978, 0.21253404])

In [96]:
divide

array([1.13311408, 0.6476565 , 1.54014262, 3.77689099, 1.29263832,
       1.14718711, 3.92501375, 0.96200679, 0.92008371, 0.54446977])

In [97]:
dot

3.4110695435029372

In [98]:
#stat functions 
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([])
mins = np.min(list1)
maxs = np.max(list1)


In [99]:
maxs

0.8762202212049689

In [100]:
data

array([[[0.74787687, 0.23371111, 0.68597185, 0.9144645 ],
        [0.88541515, 0.72853479, 0.28201572, 0.45144807],
        [0.11069352, 0.67192323, 0.86386788, 0.44515546]],

       [[0.18598314, 0.93517955, 0.38444154, 0.03532012],
        [0.62706473, 0.49197108, 0.59434518, 0.67246978],
        [0.96372605, 0.40979046, 0.79372034, 0.73144647]]])

In [101]:
mins

0.2604919273409212

In [102]:
exp

array([], dtype=float64)

In [103]:
log

3.2188758248682006

In [104]:
power

128

In [105]:
ab

2

In [106]:
sqrt 

5.0

In [107]:
data[0][0][0] = 700

In [108]:
data

array([[[7.00000000e+02, 2.33711113e-01, 6.85971846e-01, 9.14464497e-01],
        [8.85415148e-01, 7.28534792e-01, 2.82015715e-01, 4.51448073e-01],
        [1.10693523e-01, 6.71923230e-01, 8.63867879e-01, 4.45155458e-01]],

       [[1.85983144e-01, 9.35179548e-01, 3.84441541e-01, 3.53201197e-02],
        [6.27064727e-01, 4.91971084e-01, 5.94345178e-01, 6.72469779e-01],
        [9.63726053e-01, 4.09790455e-01, 7.93720341e-01, 7.31446468e-01]]])

In [109]:
data.sort()
data

array([[[2.33711113e-01, 6.85971846e-01, 9.14464497e-01, 7.00000000e+02],
        [2.82015715e-01, 4.51448073e-01, 7.28534792e-01, 8.85415148e-01],
        [1.10693523e-01, 4.45155458e-01, 6.71923230e-01, 8.63867879e-01]],

       [[3.53201197e-02, 1.85983144e-01, 3.84441541e-01, 9.35179548e-01],
        [4.91971084e-01, 5.94345178e-01, 6.27064727e-01, 6.72469779e-01],
        [4.09790455e-01, 7.31446468e-01, 7.93720341e-01, 9.63726053e-01]]])

In [110]:
print(data.shape)

(2, 3, 4)


In [111]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [112]:
zeroes = np.zeros(8)
print(zeroes)
zeroes = np.append(zeroes,[3,4])
print(zeroes)


[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [113]:
zeroes = np.insert(zeroes,2,1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


DELETE 

In [115]:
data

array([[[2.33711113e-01, 6.85971846e-01, 9.14464497e-01, 7.00000000e+02,
         2.82015715e-01, 4.51448073e-01],
        [7.28534792e-01, 8.85415148e-01, 1.10693523e-01, 4.45155458e-01,
         6.71923230e-01, 8.63867879e-01]],

       [[3.53201197e-02, 1.85983144e-01, 3.84441541e-01, 9.35179548e-01,
         4.91971084e-01, 5.94345178e-01],
        [6.27064727e-01, 6.72469779e-01, 4.09790455e-01, 7.31446468e-01,
         7.93720341e-01, 9.63726053e-01]]])

In [116]:
np.delete(data,0,axis=1)


array([[[0.72853479, 0.88541515, 0.11069352, 0.44515546, 0.67192323,
         0.86386788]],

       [[0.62706473, 0.67246978, 0.40979046, 0.73144647, 0.79372034,
         0.96372605]]])

In [117]:
np.save("new array",data)
test = np.load("new array.npy")


In [ ]:
test