<a href="https://colab.research.google.com/github/ashishb321/DATA-VIZ/blob/main/numpy_artithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np 
a = np.array([5,6,9])
a[0]

5

In [31]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [32]:
a = np.array([5,6,9])
a.ndim

1

In [33]:
a.size

3

In [34]:
a.shape

(3,)

In [35]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.arange(1,5)

array([1, 2, 3, 4])

In [38]:
np.arange(1,5,2)

array([1, 3])

In [39]:

np.sqrt(a)

array([2.23606798, 2.44948974, 3.        ])

In [40]:
np.std(a)

1.699673171197595

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#all arithmetic ops can be performed and also matrix transformation operatons can also be done

In [42]:
a+b

array([[ 6,  8],
       [10, 12]])

In [44]:
a*b

array([[ 5, 12],
       [21, 32]])

In [43]:
a.dot(b)

array([[19, 22],
       [43, 50]])